### ISSUE TITLE
Support external libraries licenses

### ISSUE THREAD

**Issue by hani-ibrahim** [zalando-incubator/zalando-commerce-ios#787]
Adding the license of the external libraries used in the framework and the demo in addition to MIT for our project 

More Info: https://github.com/zalando/zalando-howto-open-source#about-licensing

**Comment by mrandi** [comment]
@hani-ibrahim do you know any tool we could use to have this list dynamic?

**Comment by hani-ibrahim** [comment]
unfortunately no AFAIK
